drop database ex1;
drop database ex2;
drop database ex3;
drop database ex4;
drop database ex5;
drop database ex6;
drop database ex7;
drop database ex8;
drop database ex9;
SET SQL_SAFE_UPDATES=0;
drop database blackdevil;
